# Generated by Django 4.1.1 on 2022-10-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('company', models.CharField(max_length=20, verbose_name='Компания')),
                ('email', models.CharField(max_length=20, verbose_name='Почта')),
                ('cell', models.CharField(max_length=20, verbose_name='Телефон')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
    ]
