# Generated by Django 4.1.6 on 2023-03-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0004_privatenote_message_from_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Тексты',
                'verbose_name_plural': 'Текст',
                'abstract': False,
            },
        ),
    ]
