# Generated by Django 4.1.6 on 2023-03-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp_app', '0005_note_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseTemp',
            fields=[
            ],
            options={
                'ordering': ['-order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('temp_app.temp',),
        ),
    ]
