# Generated by Django 4.1.6 on 2023-02-08 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_bb_rubric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='imgfield',
        ),
        migrations.AlterField(
            model_name='aa',
            name='title',
            field=models.CharField(default='NothingHere', max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Товар'),
        ),
    ]
