# Generated by Django 4.1.6 on 2023-03-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_training_imgfield_alter_aa_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='spares',
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.machine')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.spare')),
            ],
        ),
    ]
