# Generated by Django 4.1.6 on 2023-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_machine_spares_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(to='main.spare'),
        ),
    ]
