# Generated by Django 4.1.6 on 2023-03-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_machine_spares'),
    ]

    operations = [
    ]
