# Generated by Django 4.1.6 on 2023-03-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_machine_spares'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(through='main.Kit', to='main.spare'),
        ),
    ]
