# Generated by Django 4.1.6 on 2023-03-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_note'),
    ]

    operations = [
    ]
